DROP DATABASE IF EXISTS PROYECTO_FIS;
CREATE DATABASE PROYECTO_FIS;
USE PROYECTO_FIS;

DROP TABLE IF EXISTS 
    ADMINISTRADOR, ACTIVIDAD, ALTERNATIVAS, JUGADOR, ESTADISTICAS, SECCION_ALTERNATIVAS;

CREATE TABLE ADMINISTRADOR
(
    ID CHAR(5) ,
    NICKNAME VARCHAR(100) NOT NULL,
    CONSTRAINT PK_ADMINISTRADOR PRIMARY KEY(ID)
);

CREATE TABLE ACTIVIDAD
(
    ID CHAR(7) ,
    DIFICULTAD VARCHAR(15) NOT NULL,
    TEMA VARCHAR(50) NOT NULL,
    RESPUESTA VARCHAR(50) NOT NULL,
    CONSTRAINT PK_ACTIVIDAD PRIMARY KEY(ID)
);

CREATE TABLE ALTERNATIVAS
(
    ID_ACTIVIDAD VARCHAR(7) ,
    ALTER1 VARCHAR(25) NOT NULL,
    ALTER2 VARCHAR(25) NOT NULL,
    ALTER3 VARCHAR(25) NOT NULL,
    ALTER4 VARCHAR(25) NOT NULL,
    CONSTRAINT FK_ACTIVIDAD FOREIGN KEY(ID_ACTIVIDAD) REFERENCES ACTIVIDAD(ID), 
    CONSTRAINT PK_ALTERNATIVAS PRIMARY KEY(ID_ACTIVIDAD)
);

CREATE TABLE ESTADISTICAS
(
    ID VARCHAR(7),
    ESTA_VERSION VARCHAR (50) NOT NULL, 
     CONSTRAINT PK_ESTADISTICA PRIMARY KEY(ID)
);

CREATE TABLE JUGADOR
(
    ID CHAR(10) ,
    NICKNAME VARCHAR(100) NOT NULL,
    ID_ESTADISTICAS VARCHAR(7),
    CONSTRAINT FK_JUGADOR_ESTADISTICAS FOREIGN KEY(ID_ESTADISTICAS) REFERENCES ESTADISTICAS(ID),
    CONSTRAINT PK_JUGADOR PRIMARY KEY(ID) 
);

CREATE TABLE SELECCION_ALTERNATIVA
(
    ID_JUGADOR VARCHAR(10),
    ID_ACTIVIDAD VARCHAR(7),
    CONSTRAINT PK_SELECCION_ALTERNATIVA PRIMARY KEY(ID_JUGADOR, ID_ACTIVIDAD),
    CONSTRAINT FK_ID_JUGADPR_JUGADOR FOREIGN KEY(ID_JUGADOR) REFERENCES JUGADOR(ID),
    CONSTRAINT FK_ID_ACTIVIDAD_ACTIVIDAD FOREIGN KEY(ID_ACTIVIDAD) REFERENCES ACTIVIDAD(ID)
);

